// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCalidad.Api.Data;

#nullable disable

namespace SistemaCalidad.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105173618_AgregarCarpetasRegistros")]
    partial class AgregarCarpetasRegistros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaCalidad.Api.Models.AccionCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsEficaz")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCompromiso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoConformidadId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionesVerificacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NoConformidadId");

                    b.ToTable("AccionesCalidad");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.AuditoriaAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaAccesos");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.CarpetaRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarpetasRegistros");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("VersionActual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.DocumentoExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnlaceWeb")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VersionExterna")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentosExternos");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.NoConformidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalisisCausa")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionHallazgo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetectadoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableAnalisis")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("NoConformidades");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.RegistroCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnosRetencion")
                        .HasColumnType("int");

                    b.Property<int?>("CarpetaRegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaAlmacenamiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetodoProteccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionAlmacenamiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarpetaRegistroId");

                    b.ToTable("RegistrosCalidad");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.UsuarioExterno", b =>
                {
                    b.Property<string>("idUsuario")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("idUsuario");

                    b.Property<int>("activo")
                        .HasColumnType("int")
                        .HasColumnName("Activo");

                    b.Property<string>("email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Contrasena");

                    b.HasKey("idUsuario");

                    b.ToTable("usuario", "sige_sam_v3");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.UsuarioPermiso", b =>
                {
                    b.Property<int>("UsuarioIdExterno")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioIdExterno");

                    b.ToTable("usuariospermisos", "sistemacalidad_nch2728");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.VersionDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprobadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionCambio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsVersionActual")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("VersionesDocumento");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.AccionCalidad", b =>
                {
                    b.HasOne("SistemaCalidad.Api.Models.NoConformidad", "NoConformidad")
                        .WithMany("Acciones")
                        .HasForeignKey("NoConformidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoConformidad");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.RegistroCalidad", b =>
                {
                    b.HasOne("SistemaCalidad.Api.Models.CarpetaRegistro", "Carpeta")
                        .WithMany()
                        .HasForeignKey("CarpetaRegistroId");

                    b.Navigation("Carpeta");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.VersionDocumento", b =>
                {
                    b.HasOne("SistemaCalidad.Api.Models.Documento", "Documento")
                        .WithMany("Revisiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.Documento", b =>
                {
                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("SistemaCalidad.Api.Models.NoConformidad", b =>
                {
                    b.Navigation("Acciones");
                });
#pragma warning restore 612, 618
        }
    }
}
